name: DeploymentPhpPackagist

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install packagist deployment trigger dependencies
        run: mkdir .packagistDeployTrigger && cd .packagistDeployTrigger && composer require hughcube/github-event-trigger:dev-master --prefer-dist --no-progress --no-suggest --no-interaction -vvv

      - name: Trigger deployment
        run: .packagistDeployTrigger/vendor/bin/githubEventTrigger deployment --auth_http_token=${{ secrets.PACKAGIST_TOKEN }} --repository=hughcube/php-packagist
